hydra:
  run:
    dir: debug
  output_subdir: null

defaults:
  - _self_
  - task: scene_bedroom #scene_bedroom #scene_livingroom #scene_diningroom
  - visualizer: topdown

output_directory: data/pickled_data
bbox_padding: 0.0
pointcloud_size: 30000


no_texture: false
without_floor: false
add_objfeats: true

BASE_DIR: /home/yandan/workspace/PhyScene
PATH_TO_SCENES: "data/threed_front.pkl"     

3DFRONT_dir: /home/yandan/dataset/3D-scene
path_to_floor_plan_textures: ${3DFRONT_dir}/3D-FRONT-texture/
dataset:
# for object autoencoder
  dataset_directory: ${3DFRONT_dir}/3D-FRONT/
  path_to_3d_front_dataset_directory: ${3DFRONT_dir}/3D-FRONT
  path_to_3d_future_dataset_directory: ${3DFRONT_dir}/3D-FUTURE-model
  path_to_models : ${3DFRONT_dir}/3D-FUTURE-model
  path_to_model_info: ${3DFRONT_dir}/3D-FUTURE-model/model_info.json
  
GAPartNet:
  pickled_GPN_dir: "/home/yandan/workspace/GAPartNet/dataset"
  # GPN_open_ratio: "/home/yandan/workspace/PhyScene/data/GPN_open_ratio.json"
  path_to_models: "/home/yandan/dataset/partnet_mobility_part/"
  ID_PATH: '/home/yandan/workspace/GAPartNet/dataset/render_tools/meta/partnet_all_id_list.txt'
